// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XamarinNativeNavigation.iOS
{
	public partial class SecondSBViewController : UIViewController
	{
		public SecondSBViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Title = "Second";
            NavigateButton.TouchUpInside += NavigateButton_TouchUpInside;
        }

        private void NavigateButton_TouchUpInside(object sender, EventArgs e)
        {
            var vc2 = new UINavigationController(new ThirdViewController());
            UIApplication.SharedApplication.KeyWindow.RootViewController = vc2;

        }
    }
}
